// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';
import 'value_objects.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Device>>
abstract class Device implements RustOpaqueInterface {
  BatteryInfo? get batteryStatus;

  DeviceCapabilities get capabilities;

  DateTime get connectedAt;

  DeviceType get deviceType;

  String get id;

  DateTime get lastSeen;

  String get name;

  set batteryStatus(BatteryInfo? batteryStatus);

  set capabilities(DeviceCapabilities capabilities);

  set connectedAt(DateTime connectedAt);

  set deviceType(DeviceType deviceType);

  set id(String id);

  set lastSeen(DateTime lastSeen);

  set name(String name);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Device> newInstance({
    required String id,
    required String name,
    required DeviceType deviceType,
    required DeviceCapabilities capabilities,
  }) => RustBridge.instance.api.crateDomainEntitiesDeviceNew(
    id: id,
    name: name,
    deviceType: deviceType,
    capabilities: capabilities,
  );

  Future<void> updateBattery({required BatteryInfo battery});

  Future<void> updateLastSeen();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NavigationSession>>
abstract class NavigationSession implements RustOpaqueInterface {
  Position get currentPosition;

  UuidValue get id;

  Route get route;

  DateTime get startedAt;

  NavigationStatus get status;

  DateTime get updatedAt;

  set currentPosition(Position currentPosition);

  set id(UuidValue id);

  set route(Route route);

  set startedAt(DateTime startedAt);

  set status(NavigationStatus status);

  set updatedAt(DateTime updatedAt);

  Future<void> complete();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<NavigationSession> newInstance({
    required Route route,
    required Position initialPosition,
  }) => RustBridge.instance.api.crateDomainEntitiesNavigationSessionNew(
    route: route,
    initialPosition: initialPosition,
  );

  Future<void> pause();

  Future<void> resume();

  Future<void> updatePosition({required Position position});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Route>>
abstract class Route implements RustOpaqueInterface {
  DateTime get createdAt;

  double get distanceMeters;

  int get durationSeconds;

  UuidValue get id;

  List<Position> get polyline;

  List<Waypoint> get waypoints;

  set createdAt(DateTime createdAt);

  set distanceMeters(double distanceMeters);

  set durationSeconds(int durationSeconds);

  set id(UuidValue id);

  set polyline(List<Position> polyline);

  set waypoints(List<Waypoint> waypoints);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Route> newInstance({
    required List<Waypoint> waypoints,
    required List<Position> polyline,
    required double distanceMeters,
    required int durationSeconds,
  }) => RustBridge.instance.api.crateDomainEntitiesRouteNew(
    waypoints: waypoints,
    polyline: polyline,
    distanceMeters: distanceMeters,
    durationSeconds: durationSeconds,
  );

  Future<BigInt> totalWaypoints();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TrafficEvent>>
abstract class TrafficEvent implements RustOpaqueInterface {
  int get delaySeconds;

  String get description;

  int get distanceAheadMeters;

  UuidValue get id;

  Position get position;

  DateTime get reportedAt;

  TrafficSeverity get severity;

  set delaySeconds(int delaySeconds);

  set description(String description);

  set distanceAheadMeters(int distanceAheadMeters);

  set id(UuidValue id);

  set position(Position position);

  set reportedAt(DateTime reportedAt);

  set severity(TrafficSeverity severity);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<TrafficEvent> newInstance({
    required Position position,
    required TrafficSeverity severity,
    required int delaySeconds,
    required int distanceAheadMeters,
    required String description,
  }) => RustBridge.instance.api.crateDomainEntitiesTrafficEventNew(
    position: position,
    severity: severity,
    delaySeconds: delaySeconds,
    distanceAheadMeters: distanceAheadMeters,
    description: description,
  );
}

enum DeviceType { wearOsWatch, customBleDevice, smartphone }

enum NavigationStatus { active, paused, completed, cancelled }

enum TrafficSeverity { unknown, low, medium, high, critical }
