// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'entities.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';
import 'value_objects.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DeviceConnectedEvent>>
abstract class DeviceConnectedEvent implements RustOpaqueInterface {
  String get deviceId;

  DeviceType get deviceType;

  UuidValue get eventId;

  DateTime get occurredAt;

  set deviceId(String deviceId);

  set deviceType(DeviceType deviceType);

  set eventId(UuidValue eventId);

  set occurredAt(DateTime occurredAt);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<DeviceConnectedEvent> newInstance({
    required String deviceId,
    required DeviceType deviceType,
  }) => RustBridge.instance.api.crateDomainEventsDeviceConnectedEventNew(
    deviceId: deviceId,
    deviceType: deviceType,
  );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NavigationCompletedEvent>>
abstract class NavigationCompletedEvent implements RustOpaqueInterface {
  UuidValue get eventId;

  DateTime get occurredAt;

  UuidValue get sessionId;

  double get totalDistanceMeters;

  int get totalDurationSeconds;

  set eventId(UuidValue eventId);

  set occurredAt(DateTime occurredAt);

  set sessionId(UuidValue sessionId);

  set totalDistanceMeters(double totalDistanceMeters);

  set totalDurationSeconds(int totalDurationSeconds);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<NavigationCompletedEvent> newInstance({
    required UuidValue sessionId,
    required double totalDistanceMeters,
    required int totalDurationSeconds,
  }) => RustBridge.instance.api.crateDomainEventsNavigationCompletedEventNew(
    sessionId: sessionId,
    totalDistanceMeters: totalDistanceMeters,
    totalDurationSeconds: totalDurationSeconds,
  );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NavigationStartedEvent>>
abstract class NavigationStartedEvent implements RustOpaqueInterface {
  UuidValue get eventId;

  DateTime get occurredAt;

  UuidValue get routeId;

  UuidValue get sessionId;

  set eventId(UuidValue eventId);

  set occurredAt(DateTime occurredAt);

  set routeId(UuidValue routeId);

  set sessionId(UuidValue sessionId);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<NavigationStartedEvent> newInstance({
    required UuidValue sessionId,
    required UuidValue routeId,
  }) => RustBridge.instance.api.crateDomainEventsNavigationStartedEventNew(
    sessionId: sessionId,
    routeId: routeId,
  );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PositionUpdatedEvent>>
abstract class PositionUpdatedEvent implements RustOpaqueInterface {
  UuidValue get eventId;

  DateTime get occurredAt;

  Position get position;

  UuidValue get sessionId;

  set eventId(UuidValue eventId);

  set occurredAt(DateTime occurredAt);

  set position(Position position);

  set sessionId(UuidValue sessionId);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<PositionUpdatedEvent> newInstance({
    required UuidValue sessionId,
    required Position position,
  }) => RustBridge.instance.api.crateDomainEventsPositionUpdatedEventNew(
    sessionId: sessionId,
    position: position,
  );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TrafficAlertDetectedEvent>>
abstract class TrafficAlertDetectedEvent implements RustOpaqueInterface {
  UuidValue get eventId;

  DateTime get occurredAt;

  UuidValue get sessionId;

  TrafficEvent get trafficEvent;

  set eventId(UuidValue eventId);

  set occurredAt(DateTime occurredAt);

  set sessionId(UuidValue sessionId);

  set trafficEvent(TrafficEvent trafficEvent);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<TrafficAlertDetectedEvent> newInstance({
    required UuidValue sessionId,
    required TrafficEvent trafficEvent,
  }) => RustBridge.instance.api.crateDomainEventsTrafficAlertDetectedEventNew(
    sessionId: sessionId,
    trafficEvent: trafficEvent,
  );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WaypointReachedEvent>>
abstract class WaypointReachedEvent implements RustOpaqueInterface {
  UuidValue get eventId;

  DateTime get occurredAt;

  Position get position;

  UuidValue get sessionId;

  BigInt get waypointIndex;

  set eventId(UuidValue eventId);

  set occurredAt(DateTime occurredAt);

  set position(Position position);

  set sessionId(UuidValue sessionId);

  set waypointIndex(BigInt waypointIndex);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<WaypointReachedEvent> newInstance({
    required UuidValue sessionId,
    required BigInt waypointIndex,
    required Position position,
  }) => RustBridge.instance.api.crateDomainEventsWaypointReachedEventNew(
    sessionId: sessionId,
    waypointIndex: waypointIndex,
    position: position,
  );
}

abstract class DomainEvent {
  Future<UuidValue> aggregateId();

  Future<UuidValue> eventId();

  Future<DateTime> occurredAt();
}
