// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_context`, `route_to_dto`, `session_to_dto`
// These functions are ignored because they have generic arguments: `send_control_command`, `send_position_update`, `send_route_blob`, `send_route_summary`, `send_traffic_alert`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GeocodingResultDto`, `MockDeviceComm`, `NavigationSessionDto`, `RouteDto`, `WaypointDto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// Calculate a route between waypoints
Future<String> calculateRoute({required List<(double, double)> waypoints}) =>
    RustBridge.instance.api.crateApiV2CalculateRoute(waypoints: waypoints);

/// Start a new navigation session
Future<String> startNavigationSession({
  required List<(double, double)> waypoints,
  required (double, double) currentPosition,
}) => RustBridge.instance.api.crateApiV2StartNavigationSession(
  waypoints: waypoints,
  currentPosition: currentPosition,
);

/// Update current position during navigation
Future<void> updateNavigationPosition({
  required String sessionId,
  required double latitude,
  required double longitude,
}) => RustBridge.instance.api.crateApiV2UpdateNavigationPosition(
  sessionId: sessionId,
  latitude: latitude,
  longitude: longitude,
);

/// Get the currently active navigation session
Future<String?> getActiveSession() =>
    RustBridge.instance.api.crateApiV2GetActiveSession();

/// Pause active navigation
Future<void> pauseNavigation({required String sessionId}) =>
    RustBridge.instance.api.crateApiV2PauseNavigation(sessionId: sessionId);

/// Resume paused navigation
Future<void> resumeNavigation({required String sessionId}) =>
    RustBridge.instance.api.crateApiV2ResumeNavigation(sessionId: sessionId);

/// Stop/complete navigation
Future<void> stopNavigation({
  required String sessionId,
  required bool completed,
}) => RustBridge.instance.api.crateApiV2StopNavigation(
  sessionId: sessionId,
  completed: completed,
);

/// Search for locations by address/name
Future<String> geocodeSearch({required String query, int? limit}) =>
    RustBridge.instance.api.crateApiV2GeocodeSearch(query: query, limit: limit);

/// Reverse geocode coordinates to address
Future<String> reverseGeocode({
  required double latitude,
  required double longitude,
}) => RustBridge.instance.api.crateApiV2ReverseGeocode(
  latitude: latitude,
  longitude: longitude,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AppContext>>
abstract class AppContext implements RustOpaqueInterface {
  ArcGeocodingService get geocodingService;

  ArcNavigationRepository get navigationRepo;

  ArcRouteService get routeService;

  set geocodingService(ArcGeocodingService geocodingService);

  set navigationRepo(ArcNavigationRepository navigationRepo);

  set routeService(ArcRouteService routeService);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<AppContext> newInstance() =>
      RustBridge.instance.api.crateApiV2AppContextNew();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < dyn GeocodingService >>>
abstract class ArcGeocodingService implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < dyn NavigationRepository >>>
abstract class ArcNavigationRepository implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < dyn RouteService >>>
abstract class ArcRouteService implements RustOpaqueInterface {}
