// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

class DerivedInstructionDto {
  final String kind;
  final double distanceToNextM;
  final String? streetName;

  const DerivedInstructionDto({
    required this.kind,
    required this.distanceToNextM,
    this.streetName,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ distanceToNextM.hashCode ^ streetName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DerivedInstructionDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          distanceToNextM == other.distanceToNextM &&
          streetName == other.streetName;
}

class GeocodingResultDto {
  final double latitude;
  final double longitude;
  final String displayName;
  final String? name;
  final String? city;
  final String? country;
  final String? osmType;
  final PlatformInt64? osmId;

  const GeocodingResultDto({
    required this.latitude,
    required this.longitude,
    required this.displayName,
    this.name,
    this.city,
    this.country,
    this.osmType,
    this.osmId,
  });

  @override
  int get hashCode =>
      latitude.hashCode ^
      longitude.hashCode ^
      displayName.hashCode ^
      name.hashCode ^
      city.hashCode ^
      country.hashCode ^
      osmType.hashCode ^
      osmId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GeocodingResultDto &&
          runtimeType == other.runtimeType &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          displayName == other.displayName &&
          name == other.name &&
          city == other.city &&
          country == other.country &&
          osmType == other.osmType &&
          osmId == other.osmId;
}

class NavigationSessionDto {
  final String id;
  final RouteDto route;
  final double currentLatitude;
  final double currentLongitude;
  final String status;

  const NavigationSessionDto({
    required this.id,
    required this.route,
    required this.currentLatitude,
    required this.currentLongitude,
    required this.status,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      route.hashCode ^
      currentLatitude.hashCode ^
      currentLongitude.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NavigationSessionDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          route == other.route &&
          currentLatitude == other.currentLatitude &&
          currentLongitude == other.currentLongitude &&
          status == other.status;
}

class NavigationStateDto {
  final int currentStep;
  final DerivedInstructionDto currentInstruction;
  final DerivedInstructionDto? nextInstruction;
  final double distanceToNextM;
  final double distanceRemainingM;
  final BigInt etaSeconds;
  final bool isOffRoute;
  final double distanceFromRouteM;
  final double snappedLat;
  final double snappedLon;
  final List<String> constraintAlerts;

  const NavigationStateDto({
    required this.currentStep,
    required this.currentInstruction,
    this.nextInstruction,
    required this.distanceToNextM,
    required this.distanceRemainingM,
    required this.etaSeconds,
    required this.isOffRoute,
    required this.distanceFromRouteM,
    required this.snappedLat,
    required this.snappedLon,
    required this.constraintAlerts,
  });

  @override
  int get hashCode =>
      currentStep.hashCode ^
      currentInstruction.hashCode ^
      nextInstruction.hashCode ^
      distanceToNextM.hashCode ^
      distanceRemainingM.hashCode ^
      etaSeconds.hashCode ^
      isOffRoute.hashCode ^
      distanceFromRouteM.hashCode ^
      snappedLat.hashCode ^
      snappedLon.hashCode ^
      constraintAlerts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NavigationStateDto &&
          runtimeType == other.runtimeType &&
          currentStep == other.currentStep &&
          currentInstruction == other.currentInstruction &&
          nextInstruction == other.nextInstruction &&
          distanceToNextM == other.distanceToNextM &&
          distanceRemainingM == other.distanceRemainingM &&
          etaSeconds == other.etaSeconds &&
          isOffRoute == other.isOffRoute &&
          distanceFromRouteM == other.distanceFromRouteM &&
          snappedLat == other.snappedLat &&
          snappedLon == other.snappedLon &&
          constraintAlerts == other.constraintAlerts;
}

class RouteDto {
  final String id;
  final List<WaypointDto> waypoints;
  final double distanceMeters;
  final int durationSeconds;
  final String polylineJson;

  const RouteDto({
    required this.id,
    required this.waypoints,
    required this.distanceMeters,
    required this.durationSeconds,
    required this.polylineJson,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      waypoints.hashCode ^
      distanceMeters.hashCode ^
      durationSeconds.hashCode ^
      polylineJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RouteDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          waypoints == other.waypoints &&
          distanceMeters == other.distanceMeters &&
          durationSeconds == other.durationSeconds &&
          polylineJson == other.polylineJson;
}

class SessionStatsDto {
  final double totalDistanceM;
  final PlatformInt64 totalDurationSeconds;
  final PlatformInt64 sessionCount;

  const SessionStatsDto({
    required this.totalDistanceM,
    required this.totalDurationSeconds,
    required this.sessionCount,
  });

  @override
  int get hashCode =>
      totalDistanceM.hashCode ^
      totalDurationSeconds.hashCode ^
      sessionCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionStatsDto &&
          runtimeType == other.runtimeType &&
          totalDistanceM == other.totalDistanceM &&
          totalDurationSeconds == other.totalDurationSeconds &&
          sessionCount == other.sessionCount;
}

class WaypointDto {
  final double latitude;
  final double longitude;
  final String? name;

  const WaypointDto({
    required this.latitude,
    required this.longitude,
    this.name,
  });

  @override
  int get hashCode => latitude.hashCode ^ longitude.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WaypointDto &&
          runtimeType == other.runtimeType &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          name == other.name;
}
