// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustBridge
    extends BaseEntrypoint<RustBridgeApi, RustBridgeApiImpl, RustBridgeWire> {
  @internal
  static final instance = RustBridge._();

  RustBridge._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustBridgeApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustBridgeApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustBridgeApiImpl, RustBridgeWire>
  get apiImplConstructor => RustBridgeApiImpl.new;

  @override
  WireConstructor<RustBridgeWire> get wireConstructor =>
      RustBridgeWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1747876179;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'nav_e_ffi',
        ioDirectory: 'native/nav_e_ffi/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustBridgeApi extends BaseApi {
  Future<String> crateCalculateRoute({
    required List<(double, double)> waypoints,
  });

  List<Uint8List> crateChunkMessageForBle({
    required List<int> messageBytes,
    required String routeId,
    required int mtu,
  });

  Uint8List crateCreateControlMessage({
    required String routeId,
    required String commandType,
    required int statusCode,
    required String message,
  });

  void crateDeleteDevice({required PlatformInt64 id});

  void crateDeleteOfflineRegion({required String id});

  void crateDeleteSavedPlace({required PlatformInt64 id});

  bool crateDeviceExistsByRemoteId({required String remoteId});

  String crateDownloadOfflineRegion({
    required String name,
    required double north,
    required double south,
    required double east,
    required double west,
    required int minZoom,
    required int maxZoom,
    String? tileUrlTemplate,
  });

  Future<String> crateGeocodeSearch({required String query, int? limit});

  Future<String?> crateGetActiveSession();

  String crateGetAllDevices();

  String crateGetAllOfflineRegions();

  String crateGetAllSavedPlaces();

  String crateGetDeviceById({required PlatformInt64 id});

  String crateGetDeviceByRemoteId({required String remoteId});

  String crateGetOfflineRegionById({required String id});

  String crateGetOfflineRegionForViewport({
    required double north,
    required double south,
    required double east,
    required double west,
  });

  Uint8List crateGetOfflineRegionTileBytes({
    required String regionId,
    required int z,
    required int x,
    required int y,
  });

  String crateGetOfflineRegionTileList({required String regionId});

  String crateGetOfflineRegionsStoragePath();

  String crateGetSavedPlaceById({required PlatformInt64 id});

  Future<void> crateInitializeDatabase({required String dbPath});

  Future<void> cratePauseNavigation({required String sessionId});

  Uint8List cratePrepareMapRegionMetadataMessage({
    required String regionJson,
    required int totalTiles,
  });

  Uint8List cratePrepareMapStyleMessage({required String mapSourceId});

  Uint8List cratePrepareRouteMessage({required String routeJson});

  Uint8List cratePrepareTileChunkMessage({
    required String regionId,
    required int z,
    required int x,
    required int y,
    required List<int> data,
  });

  Uint8List crateReassembleFrames({required List<Uint8List> frameBytes});

  Future<void> crateResumeNavigation({required String sessionId});

  Future<String> crateReverseGeocode({
    required double latitude,
    required double longitude,
  });

  PlatformInt64 crateSaveDevice({required String deviceJson});

  PlatformInt64 crateSavePlace({
    required String name,
    String? address,
    required double lat,
    required double lon,
    String? source,
    PlatformInt64? typeId,
    String? remoteId,
  });

  Future<void> crateSendRouteToDevice({
    required PlatformInt64 deviceId,
    required String routeJson,
  });

  Future<String> crateStartNavigationSession({
    required List<(double, double)> waypoints,
    required (double, double) currentPosition,
  });

  Future<void> crateStopNavigation({required String sessionId});

  void crateUpdateDevice({
    required PlatformInt64 id,
    required String deviceJson,
  });

  Future<void> crateUpdateNavigationPosition({
    required String sessionId,
    required double latitude,
    required double longitude,
  });
}

class RustBridgeApiImpl extends RustBridgeApiImplPlatform
    implements RustBridgeApi {
  RustBridgeApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateCalculateRoute({
    required List<(double, double)> waypoints,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_record_f_64_f_64(waypoints, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateCalculateRouteConstMeta,
        argValues: [waypoints],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCalculateRouteConstMeta => const TaskConstMeta(
    debugName: "calculate_route",
    argNames: ["waypoints"],
  );

  @override
  List<Uint8List> crateChunkMessageForBle({
    required List<int> messageBytes,
    required String routeId,
    required int mtu,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(messageBytes, serializer);
          sse_encode_String(routeId, serializer);
          sse_encode_u_32(mtu, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateChunkMessageForBleConstMeta,
        argValues: [messageBytes, routeId, mtu],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateChunkMessageForBleConstMeta => const TaskConstMeta(
    debugName: "chunk_message_for_ble",
    argNames: ["messageBytes", "routeId", "mtu"],
  );

  @override
  Uint8List crateCreateControlMessage({
    required String routeId,
    required String commandType,
    required int statusCode,
    required String message,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(routeId, serializer);
          sse_encode_String(commandType, serializer);
          sse_encode_u_32(statusCode, serializer);
          sse_encode_String(message, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateCreateControlMessageConstMeta,
        argValues: [routeId, commandType, statusCode, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCreateControlMessageConstMeta => const TaskConstMeta(
    debugName: "create_control_message",
    argNames: ["routeId", "commandType", "statusCode", "message"],
  );

  @override
  void crateDeleteDevice({required PlatformInt64 id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateDeleteDeviceConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateDeleteDeviceConstMeta =>
      const TaskConstMeta(debugName: "delete_device", argNames: ["id"]);

  @override
  void crateDeleteOfflineRegion({required String id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateDeleteOfflineRegionConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateDeleteOfflineRegionConstMeta =>
      const TaskConstMeta(debugName: "delete_offline_region", argNames: ["id"]);

  @override
  void crateDeleteSavedPlace({required PlatformInt64 id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateDeleteSavedPlaceConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateDeleteSavedPlaceConstMeta =>
      const TaskConstMeta(debugName: "delete_saved_place", argNames: ["id"]);

  @override
  bool crateDeviceExistsByRemoteId({required String remoteId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(remoteId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateDeviceExistsByRemoteIdConstMeta,
        argValues: [remoteId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateDeviceExistsByRemoteIdConstMeta =>
      const TaskConstMeta(
        debugName: "device_exists_by_remote_id",
        argNames: ["remoteId"],
      );

  @override
  String crateDownloadOfflineRegion({
    required String name,
    required double north,
    required double south,
    required double east,
    required double west,
    required int minZoom,
    required int maxZoom,
    String? tileUrlTemplate,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_f_64(north, serializer);
          sse_encode_f_64(south, serializer);
          sse_encode_f_64(east, serializer);
          sse_encode_f_64(west, serializer);
          sse_encode_i_32(minZoom, serializer);
          sse_encode_i_32(maxZoom, serializer);
          sse_encode_opt_String(tileUrlTemplate, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateDownloadOfflineRegionConstMeta,
        argValues: [
          name,
          north,
          south,
          east,
          west,
          minZoom,
          maxZoom,
          tileUrlTemplate,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateDownloadOfflineRegionConstMeta => const TaskConstMeta(
    debugName: "download_offline_region",
    argNames: [
      "name",
      "north",
      "south",
      "east",
      "west",
      "minZoom",
      "maxZoom",
      "tileUrlTemplate",
    ],
  );

  @override
  Future<String> crateGeocodeSearch({required String query, int? limit}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          sse_encode_opt_box_autoadd_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGeocodeSearchConstMeta,
        argValues: [query, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGeocodeSearchConstMeta => const TaskConstMeta(
    debugName: "geocode_search",
    argNames: ["query", "limit"],
  );

  @override
  Future<String?> crateGetActiveSession() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetActiveSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetActiveSessionConstMeta =>
      const TaskConstMeta(debugName: "get_active_session", argNames: []);

  @override
  String crateGetAllDevices() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetAllDevicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetAllDevicesConstMeta =>
      const TaskConstMeta(debugName: "get_all_devices", argNames: []);

  @override
  String crateGetAllOfflineRegions() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetAllOfflineRegionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetAllOfflineRegionsConstMeta =>
      const TaskConstMeta(debugName: "get_all_offline_regions", argNames: []);

  @override
  String crateGetAllSavedPlaces() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetAllSavedPlacesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetAllSavedPlacesConstMeta =>
      const TaskConstMeta(debugName: "get_all_saved_places", argNames: []);

  @override
  String crateGetDeviceById({required PlatformInt64 id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetDeviceByIdConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetDeviceByIdConstMeta =>
      const TaskConstMeta(debugName: "get_device_by_id", argNames: ["id"]);

  @override
  String crateGetDeviceByRemoteId({required String remoteId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(remoteId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetDeviceByRemoteIdConstMeta,
        argValues: [remoteId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetDeviceByRemoteIdConstMeta => const TaskConstMeta(
    debugName: "get_device_by_remote_id",
    argNames: ["remoteId"],
  );

  @override
  String crateGetOfflineRegionById({required String id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetOfflineRegionByIdConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetOfflineRegionByIdConstMeta => const TaskConstMeta(
    debugName: "get_offline_region_by_id",
    argNames: ["id"],
  );

  @override
  String crateGetOfflineRegionForViewport({
    required double north,
    required double south,
    required double east,
    required double west,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(north, serializer);
          sse_encode_f_64(south, serializer);
          sse_encode_f_64(east, serializer);
          sse_encode_f_64(west, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetOfflineRegionForViewportConstMeta,
        argValues: [north, south, east, west],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetOfflineRegionForViewportConstMeta =>
      const TaskConstMeta(
        debugName: "get_offline_region_for_viewport",
        argNames: ["north", "south", "east", "west"],
      );

  @override
  Uint8List crateGetOfflineRegionTileBytes({
    required String regionId,
    required int z,
    required int x,
    required int y,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(regionId, serializer);
          sse_encode_i_32(z, serializer);
          sse_encode_i_32(x, serializer);
          sse_encode_i_32(y, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetOfflineRegionTileBytesConstMeta,
        argValues: [regionId, z, x, y],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetOfflineRegionTileBytesConstMeta =>
      const TaskConstMeta(
        debugName: "get_offline_region_tile_bytes",
        argNames: ["regionId", "z", "x", "y"],
      );

  @override
  String crateGetOfflineRegionTileList({required String regionId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(regionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetOfflineRegionTileListConstMeta,
        argValues: [regionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetOfflineRegionTileListConstMeta =>
      const TaskConstMeta(
        debugName: "get_offline_region_tile_list",
        argNames: ["regionId"],
      );

  @override
  String crateGetOfflineRegionsStoragePath() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetOfflineRegionsStoragePathConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetOfflineRegionsStoragePathConstMeta =>
      const TaskConstMeta(
        debugName: "get_offline_regions_storage_path",
        argNames: [],
      );

  @override
  String crateGetSavedPlaceById({required PlatformInt64 id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetSavedPlaceByIdConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetSavedPlaceByIdConstMeta =>
      const TaskConstMeta(debugName: "get_saved_place_by_id", argNames: ["id"]);

  @override
  Future<void> crateInitializeDatabase({required String dbPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateInitializeDatabaseConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateInitializeDatabaseConstMeta => const TaskConstMeta(
    debugName: "initialize_database",
    argNames: ["dbPath"],
  );

  @override
  Future<void> cratePauseNavigation({required String sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCratePauseNavigationConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePauseNavigationConstMeta => const TaskConstMeta(
    debugName: "pause_navigation",
    argNames: ["sessionId"],
  );

  @override
  Uint8List cratePrepareMapRegionMetadataMessage({
    required String regionJson,
    required int totalTiles,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(regionJson, serializer);
          sse_encode_u_32(totalTiles, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCratePrepareMapRegionMetadataMessageConstMeta,
        argValues: [regionJson, totalTiles],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePrepareMapRegionMetadataMessageConstMeta =>
      const TaskConstMeta(
        debugName: "prepare_map_region_metadata_message",
        argNames: ["regionJson", "totalTiles"],
      );

  @override
  Uint8List cratePrepareMapStyleMessage({required String mapSourceId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mapSourceId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCratePrepareMapStyleMessageConstMeta,
        argValues: [mapSourceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePrepareMapStyleMessageConstMeta =>
      const TaskConstMeta(
        debugName: "prepare_map_style_message",
        argNames: ["mapSourceId"],
      );

  @override
  Uint8List cratePrepareRouteMessage({required String routeJson}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(routeJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCratePrepareRouteMessageConstMeta,
        argValues: [routeJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePrepareRouteMessageConstMeta => const TaskConstMeta(
    debugName: "prepare_route_message",
    argNames: ["routeJson"],
  );

  @override
  Uint8List cratePrepareTileChunkMessage({
    required String regionId,
    required int z,
    required int x,
    required int y,
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(regionId, serializer);
          sse_encode_i_32(z, serializer);
          sse_encode_i_32(x, serializer);
          sse_encode_i_32(y, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCratePrepareTileChunkMessageConstMeta,
        argValues: [regionId, z, x, y, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePrepareTileChunkMessageConstMeta =>
      const TaskConstMeta(
        debugName: "prepare_tile_chunk_message",
        argNames: ["regionId", "z", "x", "y", "data"],
      );

  @override
  Uint8List crateReassembleFrames({required List<Uint8List> frameBytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_list_prim_u_8_strict(frameBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateReassembleFramesConstMeta,
        argValues: [frameBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateReassembleFramesConstMeta => const TaskConstMeta(
    debugName: "reassemble_frames",
    argNames: ["frameBytes"],
  );

  @override
  Future<void> crateResumeNavigation({required String sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateResumeNavigationConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateResumeNavigationConstMeta => const TaskConstMeta(
    debugName: "resume_navigation",
    argNames: ["sessionId"],
  );

  @override
  Future<String> crateReverseGeocode({
    required double latitude,
    required double longitude,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(latitude, serializer);
          sse_encode_f_64(longitude, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateReverseGeocodeConstMeta,
        argValues: [latitude, longitude],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateReverseGeocodeConstMeta => const TaskConstMeta(
    debugName: "reverse_geocode",
    argNames: ["latitude", "longitude"],
  );

  @override
  PlatformInt64 crateSaveDevice({required String deviceJson}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateSaveDeviceConstMeta,
        argValues: [deviceJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSaveDeviceConstMeta =>
      const TaskConstMeta(debugName: "save_device", argNames: ["deviceJson"]);

  @override
  PlatformInt64 crateSavePlace({
    required String name,
    String? address,
    required double lat,
    required double lon,
    String? source,
    PlatformInt64? typeId,
    String? remoteId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_opt_String(address, serializer);
          sse_encode_f_64(lat, serializer);
          sse_encode_f_64(lon, serializer);
          sse_encode_opt_String(source, serializer);
          sse_encode_opt_box_autoadd_i_64(typeId, serializer);
          sse_encode_opt_String(remoteId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateSavePlaceConstMeta,
        argValues: [name, address, lat, lon, source, typeId, remoteId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSavePlaceConstMeta => const TaskConstMeta(
    debugName: "save_place",
    argNames: ["name", "address", "lat", "lon", "source", "typeId", "remoteId"],
  );

  @override
  Future<void> crateSendRouteToDevice({
    required PlatformInt64 deviceId,
    required String routeJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(deviceId, serializer);
          sse_encode_String(routeJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateSendRouteToDeviceConstMeta,
        argValues: [deviceId, routeJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSendRouteToDeviceConstMeta => const TaskConstMeta(
    debugName: "send_route_to_device",
    argNames: ["deviceId", "routeJson"],
  );

  @override
  Future<String> crateStartNavigationSession({
    required List<(double, double)> waypoints,
    required (double, double) currentPosition,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_record_f_64_f_64(waypoints, serializer);
          sse_encode_box_autoadd_record_f_64_f_64(currentPosition, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateStartNavigationSessionConstMeta,
        argValues: [waypoints, currentPosition],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateStartNavigationSessionConstMeta =>
      const TaskConstMeta(
        debugName: "start_navigation_session",
        argNames: ["waypoints", "currentPosition"],
      );

  @override
  Future<void> crateStopNavigation({required String sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateStopNavigationConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateStopNavigationConstMeta => const TaskConstMeta(
    debugName: "stop_navigation",
    argNames: ["sessionId"],
  );

  @override
  void crateUpdateDevice({
    required PlatformInt64 id,
    required String deviceJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          sse_encode_String(deviceJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 36)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateUpdateDeviceConstMeta,
        argValues: [id, deviceJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateUpdateDeviceConstMeta => const TaskConstMeta(
    debugName: "update_device",
    argNames: ["id", "deviceJson"],
  );

  @override
  Future<void> crateUpdateNavigationPosition({
    required String sessionId,
    required double latitude,
    required double longitude,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_f_64(latitude, serializer);
          sse_encode_f_64(longitude, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateUpdateNavigationPositionConstMeta,
        argValues: [sessionId, latitude, longitude],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateUpdateNavigationPositionConstMeta =>
      const TaskConstMeta(
        debugName: "update_navigation_position",
        argNames: ["sessionId", "latitude", "longitude"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  (double, double) dco_decode_box_autoadd_record_f_64_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as (double, double);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(double, double)> dco_decode_list_record_f_64_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_f_64_f_64).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  (double, double) dco_decode_record_f_64_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_f_64(arr[0]), dco_decode_f_64(arr[1]));
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  (double, double) sse_decode_box_autoadd_record_f_64_f_64(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_record_f_64_f_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(double, double)> sse_decode_list_record_f_64_f_64(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(double, double)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_f_64_f_64(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (double, double) sse_decode_record_f_64_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_f_64(deserializer);
    var var_field1 = sse_decode_f_64(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_record_f_64_f_64(
    (double, double) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_record_f_64_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_f_64_f_64(
    List<(double, double)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_f_64_f_64(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_record_f_64_f_64(
    (double, double) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.$1, serializer);
    sse_encode_f_64(self.$2, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
