// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'ffi_models.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustBridge
    extends BaseEntrypoint<RustBridgeApi, RustBridgeApiImpl, RustBridgeWire> {
  @internal
  static final instance = RustBridge._();

  RustBridge._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustBridgeApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustBridgeApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustBridgeApiImpl, RustBridgeWire>
  get apiImplConstructor => RustBridgeApiImpl.new;

  @override
  WireConstructor<RustBridgeWire> get wireConstructor =>
      RustBridgeWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1980456439;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'nav_e_ffi',
        ioDirectory: 'native/nav_e_ffi/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustBridgeApi extends BaseApi {
  Future<RouteDto> crateCalculateRoute({
    required List<(double, double)> waypoints,
  });

  List<Uint8List> crateChunkMessageForBle({
    required List<int> messageBytes,
    required String routeId,
    required int mtu,
  });

  Uint8List crateCreateControlMessage({
    required String routeId,
    required String commandType,
    required int statusCode,
    required String message,
  });

  void crateDeleteDevice({required PlatformInt64 id});

  void crateDeleteOfflineRegion({required String id});

  void crateDeleteSavedPlace({required PlatformInt64 id});

  void crateDeleteSavedRoute({required PlatformInt64 id});

  void crateDeleteTrip({required PlatformInt64 id});

  bool crateDeviceExistsByRemoteId({required String remoteId});

  String crateDownloadOfflineRegion({
    required String name,
    required double north,
    required double south,
    required double east,
    required double west,
    required int minZoom,
    required int maxZoom,
    String? tileUrlTemplate,
  });

  Future<List<GeocodingResultDto>> crateGeocodeSearch({
    required String query,
    int? limit,
  });

  Future<String?> crateGetActiveSession();

  String crateGetAllDevices();

  String crateGetAllOfflineRegions();

  String crateGetAllSavedPlaces();

  String crateGetAllSavedRoutes();

  String crateGetAllTrips();

  String crateGetDeviceById({required PlatformInt64 id});

  String crateGetDeviceByRemoteId({required String remoteId});

  Future<NavigationStateDto?> crateGetNavigationState({
    required String sessionId,
  });

  String crateGetOfflineRegionById({required String id});

  String crateGetOfflineRegionForViewport({
    required double north,
    required double south,
    required double east,
    required double west,
  });

  Uint8List crateGetOfflineRegionTileBytes({
    required String regionId,
    required int z,
    required int x,
    required int y,
  });

  String crateGetOfflineRegionTileList({required String regionId});

  String crateGetOfflineRegionsStoragePath();

  Future<List<DerivedInstructionDto>> crateGetRouteSteps({
    required String sessionId,
  });

  String crateGetSavedPlaceById({required PlatformInt64 id});

  String crateGetSavedRouteById({required PlatformInt64 id});

  Future<SessionStatsDto> crateGetSessionStats();

  String crateGetTripById({required PlatformInt64 id});

  String crateImportRouteFromGpx({required List<int> bytes});

  Future<void> crateInitializeDatabase({
    required String dbPath,
    String? googleRoutesApiKey,
  });

  String crateParseRouteFromGpx({required List<int> bytes});

  Future<void> cratePauseNavigation({required String sessionId});

  Uint8List cratePrepareMapRegionMetadataMessage({
    required String regionJson,
    required int totalTiles,
  });

  Uint8List cratePrepareMapStyleMessage({required String mapSourceId});

  Uint8List cratePrepareRouteMessage({required String routeJson});

  Uint8List cratePrepareTileChunkMessage({
    required String regionId,
    required int z,
    required int x,
    required int y,
    required List<int> data,
  });

  Uint8List crateReassembleFrames({required List<Uint8List> frameBytes});

  Future<void> crateResumeNavigation({required String sessionId});

  Future<String> crateReverseGeocode({
    required double latitude,
    required double longitude,
  });

  PlatformInt64 crateSaveDevice({required String deviceJson});

  PlatformInt64 crateSavePlace({
    required String name,
    String? address,
    required double lat,
    required double lon,
    String? source,
    PlatformInt64? typeId,
    String? remoteId,
  });

  String crateSaveRouteFromJson({
    required String routeJson,
    required String source,
  });

  PlatformInt64 crateSaveRouteFromPlan({
    required String name,
    required List<(double, double)> waypoints,
    String? polylineEncoded,
    double? distanceM,
    BigInt? durationS,
  });

  PlatformInt64 crateSaveTrip({
    required double distanceM,
    required PlatformInt64 durationSeconds,
    required PlatformInt64 startedAt,
    required PlatformInt64 completedAt,
    required String status,
    String? destinationLabel,
    String? routeId,
    String? polylineEncoded,
  });

  Future<void> crateSendRouteToDevice({
    required PlatformInt64 deviceId,
    required String routeJson,
  });

  Future<void> crateSetNavdspConfig({
    required String baseUrl,
    String? token,
    required bool geocodingEnabled,
  });

  Future<void> crateSetRoutingEngine({required String engine});

  Future<NavigationSessionDto> crateStartNavigationSession({
    required List<(double, double)> waypoints,
    required (double, double) currentPosition,
  });

  Future<void> crateStopNavigation({required String sessionId});

  void crateUpdateDevice({
    required PlatformInt64 id,
    required String deviceJson,
  });

  Future<NavigationStateDto> crateUpdateNavigationPosition({
    required String sessionId,
    required double latitude,
    required double longitude,
  });
}

class RustBridgeApiImpl extends RustBridgeApiImplPlatform
    implements RustBridgeApi {
  RustBridgeApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<RouteDto> crateCalculateRoute({
    required List<(double, double)> waypoints,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_record_f_64_f_64(waypoints, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_route_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateCalculateRouteConstMeta,
        argValues: [waypoints],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCalculateRouteConstMeta => const TaskConstMeta(
    debugName: "calculate_route",
    argNames: ["waypoints"],
  );

  @override
  List<Uint8List> crateChunkMessageForBle({
    required List<int> messageBytes,
    required String routeId,
    required int mtu,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(messageBytes, serializer);
          sse_encode_String(routeId, serializer);
          sse_encode_u_32(mtu, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateChunkMessageForBleConstMeta,
        argValues: [messageBytes, routeId, mtu],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateChunkMessageForBleConstMeta => const TaskConstMeta(
    debugName: "chunk_message_for_ble",
    argNames: ["messageBytes", "routeId", "mtu"],
  );

  @override
  Uint8List crateCreateControlMessage({
    required String routeId,
    required String commandType,
    required int statusCode,
    required String message,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(routeId, serializer);
          sse_encode_String(commandType, serializer);
          sse_encode_u_32(statusCode, serializer);
          sse_encode_String(message, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateCreateControlMessageConstMeta,
        argValues: [routeId, commandType, statusCode, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCreateControlMessageConstMeta => const TaskConstMeta(
    debugName: "create_control_message",
    argNames: ["routeId", "commandType", "statusCode", "message"],
  );

  @override
  void crateDeleteDevice({required PlatformInt64 id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateDeleteDeviceConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateDeleteDeviceConstMeta =>
      const TaskConstMeta(debugName: "delete_device", argNames: ["id"]);

  @override
  void crateDeleteOfflineRegion({required String id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateDeleteOfflineRegionConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateDeleteOfflineRegionConstMeta =>
      const TaskConstMeta(debugName: "delete_offline_region", argNames: ["id"]);

  @override
  void crateDeleteSavedPlace({required PlatformInt64 id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateDeleteSavedPlaceConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateDeleteSavedPlaceConstMeta =>
      const TaskConstMeta(debugName: "delete_saved_place", argNames: ["id"]);

  @override
  void crateDeleteSavedRoute({required PlatformInt64 id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateDeleteSavedRouteConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateDeleteSavedRouteConstMeta =>
      const TaskConstMeta(debugName: "delete_saved_route", argNames: ["id"]);

  @override
  void crateDeleteTrip({required PlatformInt64 id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateDeleteTripConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateDeleteTripConstMeta =>
      const TaskConstMeta(debugName: "delete_trip", argNames: ["id"]);

  @override
  bool crateDeviceExistsByRemoteId({required String remoteId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(remoteId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateDeviceExistsByRemoteIdConstMeta,
        argValues: [remoteId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateDeviceExistsByRemoteIdConstMeta =>
      const TaskConstMeta(
        debugName: "device_exists_by_remote_id",
        argNames: ["remoteId"],
      );

  @override
  String crateDownloadOfflineRegion({
    required String name,
    required double north,
    required double south,
    required double east,
    required double west,
    required int minZoom,
    required int maxZoom,
    String? tileUrlTemplate,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_f_64(north, serializer);
          sse_encode_f_64(south, serializer);
          sse_encode_f_64(east, serializer);
          sse_encode_f_64(west, serializer);
          sse_encode_i_32(minZoom, serializer);
          sse_encode_i_32(maxZoom, serializer);
          sse_encode_opt_String(tileUrlTemplate, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateDownloadOfflineRegionConstMeta,
        argValues: [
          name,
          north,
          south,
          east,
          west,
          minZoom,
          maxZoom,
          tileUrlTemplate,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateDownloadOfflineRegionConstMeta => const TaskConstMeta(
    debugName: "download_offline_region",
    argNames: [
      "name",
      "north",
      "south",
      "east",
      "west",
      "minZoom",
      "maxZoom",
      "tileUrlTemplate",
    ],
  );

  @override
  Future<List<GeocodingResultDto>> crateGeocodeSearch({
    required String query,
    int? limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          sse_encode_opt_box_autoadd_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_geocoding_result_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGeocodeSearchConstMeta,
        argValues: [query, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGeocodeSearchConstMeta => const TaskConstMeta(
    debugName: "geocode_search",
    argNames: ["query", "limit"],
  );

  @override
  Future<String?> crateGetActiveSession() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetActiveSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetActiveSessionConstMeta =>
      const TaskConstMeta(debugName: "get_active_session", argNames: []);

  @override
  String crateGetAllDevices() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetAllDevicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetAllDevicesConstMeta =>
      const TaskConstMeta(debugName: "get_all_devices", argNames: []);

  @override
  String crateGetAllOfflineRegions() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetAllOfflineRegionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetAllOfflineRegionsConstMeta =>
      const TaskConstMeta(debugName: "get_all_offline_regions", argNames: []);

  @override
  String crateGetAllSavedPlaces() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetAllSavedPlacesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetAllSavedPlacesConstMeta =>
      const TaskConstMeta(debugName: "get_all_saved_places", argNames: []);

  @override
  String crateGetAllSavedRoutes() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetAllSavedRoutesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetAllSavedRoutesConstMeta =>
      const TaskConstMeta(debugName: "get_all_saved_routes", argNames: []);

  @override
  String crateGetAllTrips() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetAllTripsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetAllTripsConstMeta =>
      const TaskConstMeta(debugName: "get_all_trips", argNames: []);

  @override
  String crateGetDeviceById({required PlatformInt64 id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetDeviceByIdConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetDeviceByIdConstMeta =>
      const TaskConstMeta(debugName: "get_device_by_id", argNames: ["id"]);

  @override
  String crateGetDeviceByRemoteId({required String remoteId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(remoteId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetDeviceByRemoteIdConstMeta,
        argValues: [remoteId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetDeviceByRemoteIdConstMeta => const TaskConstMeta(
    debugName: "get_device_by_remote_id",
    argNames: ["remoteId"],
  );

  @override
  Future<NavigationStateDto?> crateGetNavigationState({
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_navigation_state_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetNavigationStateConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetNavigationStateConstMeta => const TaskConstMeta(
    debugName: "get_navigation_state",
    argNames: ["sessionId"],
  );

  @override
  String crateGetOfflineRegionById({required String id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetOfflineRegionByIdConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetOfflineRegionByIdConstMeta => const TaskConstMeta(
    debugName: "get_offline_region_by_id",
    argNames: ["id"],
  );

  @override
  String crateGetOfflineRegionForViewport({
    required double north,
    required double south,
    required double east,
    required double west,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(north, serializer);
          sse_encode_f_64(south, serializer);
          sse_encode_f_64(east, serializer);
          sse_encode_f_64(west, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetOfflineRegionForViewportConstMeta,
        argValues: [north, south, east, west],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetOfflineRegionForViewportConstMeta =>
      const TaskConstMeta(
        debugName: "get_offline_region_for_viewport",
        argNames: ["north", "south", "east", "west"],
      );

  @override
  Uint8List crateGetOfflineRegionTileBytes({
    required String regionId,
    required int z,
    required int x,
    required int y,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(regionId, serializer);
          sse_encode_i_32(z, serializer);
          sse_encode_i_32(x, serializer);
          sse_encode_i_32(y, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetOfflineRegionTileBytesConstMeta,
        argValues: [regionId, z, x, y],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetOfflineRegionTileBytesConstMeta =>
      const TaskConstMeta(
        debugName: "get_offline_region_tile_bytes",
        argNames: ["regionId", "z", "x", "y"],
      );

  @override
  String crateGetOfflineRegionTileList({required String regionId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(regionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetOfflineRegionTileListConstMeta,
        argValues: [regionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetOfflineRegionTileListConstMeta =>
      const TaskConstMeta(
        debugName: "get_offline_region_tile_list",
        argNames: ["regionId"],
      );

  @override
  String crateGetOfflineRegionsStoragePath() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetOfflineRegionsStoragePathConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetOfflineRegionsStoragePathConstMeta =>
      const TaskConstMeta(
        debugName: "get_offline_regions_storage_path",
        argNames: [],
      );

  @override
  Future<List<DerivedInstructionDto>> crateGetRouteSteps({
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_derived_instruction_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetRouteStepsConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetRouteStepsConstMeta => const TaskConstMeta(
    debugName: "get_route_steps",
    argNames: ["sessionId"],
  );

  @override
  String crateGetSavedPlaceById({required PlatformInt64 id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetSavedPlaceByIdConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetSavedPlaceByIdConstMeta =>
      const TaskConstMeta(debugName: "get_saved_place_by_id", argNames: ["id"]);

  @override
  String crateGetSavedRouteById({required PlatformInt64 id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetSavedRouteByIdConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetSavedRouteByIdConstMeta =>
      const TaskConstMeta(debugName: "get_saved_route_by_id", argNames: ["id"]);

  @override
  Future<SessionStatsDto> crateGetSessionStats() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_stats_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetSessionStatsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetSessionStatsConstMeta =>
      const TaskConstMeta(debugName: "get_session_stats", argNames: []);

  @override
  String crateGetTripById({required PlatformInt64 id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateGetTripByIdConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateGetTripByIdConstMeta =>
      const TaskConstMeta(debugName: "get_trip_by_id", argNames: ["id"]);

  @override
  String crateImportRouteFromGpx({required List<int> bytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateImportRouteFromGpxConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateImportRouteFromGpxConstMeta => const TaskConstMeta(
    debugName: "import_route_from_gpx",
    argNames: ["bytes"],
  );

  @override
  Future<void> crateInitializeDatabase({
    required String dbPath,
    String? googleRoutesApiKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_opt_String(googleRoutesApiKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateInitializeDatabaseConstMeta,
        argValues: [dbPath, googleRoutesApiKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateInitializeDatabaseConstMeta => const TaskConstMeta(
    debugName: "initialize_database",
    argNames: ["dbPath", "googleRoutesApiKey"],
  );

  @override
  String crateParseRouteFromGpx({required List<int> bytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 33)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateParseRouteFromGpxConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateParseRouteFromGpxConstMeta => const TaskConstMeta(
    debugName: "parse_route_from_gpx",
    argNames: ["bytes"],
  );

  @override
  Future<void> cratePauseNavigation({required String sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCratePauseNavigationConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePauseNavigationConstMeta => const TaskConstMeta(
    debugName: "pause_navigation",
    argNames: ["sessionId"],
  );

  @override
  Uint8List cratePrepareMapRegionMetadataMessage({
    required String regionJson,
    required int totalTiles,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(regionJson, serializer);
          sse_encode_u_32(totalTiles, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 35)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCratePrepareMapRegionMetadataMessageConstMeta,
        argValues: [regionJson, totalTiles],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePrepareMapRegionMetadataMessageConstMeta =>
      const TaskConstMeta(
        debugName: "prepare_map_region_metadata_message",
        argNames: ["regionJson", "totalTiles"],
      );

  @override
  Uint8List cratePrepareMapStyleMessage({required String mapSourceId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mapSourceId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 36)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCratePrepareMapStyleMessageConstMeta,
        argValues: [mapSourceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePrepareMapStyleMessageConstMeta =>
      const TaskConstMeta(
        debugName: "prepare_map_style_message",
        argNames: ["mapSourceId"],
      );

  @override
  Uint8List cratePrepareRouteMessage({required String routeJson}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(routeJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 37)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCratePrepareRouteMessageConstMeta,
        argValues: [routeJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePrepareRouteMessageConstMeta => const TaskConstMeta(
    debugName: "prepare_route_message",
    argNames: ["routeJson"],
  );

  @override
  Uint8List cratePrepareTileChunkMessage({
    required String regionId,
    required int z,
    required int x,
    required int y,
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(regionId, serializer);
          sse_encode_i_32(z, serializer);
          sse_encode_i_32(x, serializer);
          sse_encode_i_32(y, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 38)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCratePrepareTileChunkMessageConstMeta,
        argValues: [regionId, z, x, y, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCratePrepareTileChunkMessageConstMeta =>
      const TaskConstMeta(
        debugName: "prepare_tile_chunk_message",
        argNames: ["regionId", "z", "x", "y", "data"],
      );

  @override
  Uint8List crateReassembleFrames({required List<Uint8List> frameBytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_list_prim_u_8_strict(frameBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 39)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateReassembleFramesConstMeta,
        argValues: [frameBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateReassembleFramesConstMeta => const TaskConstMeta(
    debugName: "reassemble_frames",
    argNames: ["frameBytes"],
  );

  @override
  Future<void> crateResumeNavigation({required String sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 40,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateResumeNavigationConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateResumeNavigationConstMeta => const TaskConstMeta(
    debugName: "resume_navigation",
    argNames: ["sessionId"],
  );

  @override
  Future<String> crateReverseGeocode({
    required double latitude,
    required double longitude,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(latitude, serializer);
          sse_encode_f_64(longitude, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 41,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateReverseGeocodeConstMeta,
        argValues: [latitude, longitude],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateReverseGeocodeConstMeta => const TaskConstMeta(
    debugName: "reverse_geocode",
    argNames: ["latitude", "longitude"],
  );

  @override
  PlatformInt64 crateSaveDevice({required String deviceJson}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 42)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateSaveDeviceConstMeta,
        argValues: [deviceJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSaveDeviceConstMeta =>
      const TaskConstMeta(debugName: "save_device", argNames: ["deviceJson"]);

  @override
  PlatformInt64 crateSavePlace({
    required String name,
    String? address,
    required double lat,
    required double lon,
    String? source,
    PlatformInt64? typeId,
    String? remoteId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_opt_String(address, serializer);
          sse_encode_f_64(lat, serializer);
          sse_encode_f_64(lon, serializer);
          sse_encode_opt_String(source, serializer);
          sse_encode_opt_box_autoadd_i_64(typeId, serializer);
          sse_encode_opt_String(remoteId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 43)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateSavePlaceConstMeta,
        argValues: [name, address, lat, lon, source, typeId, remoteId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSavePlaceConstMeta => const TaskConstMeta(
    debugName: "save_place",
    argNames: ["name", "address", "lat", "lon", "source", "typeId", "remoteId"],
  );

  @override
  String crateSaveRouteFromJson({
    required String routeJson,
    required String source,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(routeJson, serializer);
          sse_encode_String(source, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 44)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateSaveRouteFromJsonConstMeta,
        argValues: [routeJson, source],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSaveRouteFromJsonConstMeta => const TaskConstMeta(
    debugName: "save_route_from_json",
    argNames: ["routeJson", "source"],
  );

  @override
  PlatformInt64 crateSaveRouteFromPlan({
    required String name,
    required List<(double, double)> waypoints,
    String? polylineEncoded,
    double? distanceM,
    BigInt? durationS,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_list_record_f_64_f_64(waypoints, serializer);
          sse_encode_opt_String(polylineEncoded, serializer);
          sse_encode_opt_box_autoadd_f_64(distanceM, serializer);
          sse_encode_opt_box_autoadd_u_64(durationS, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 45)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateSaveRouteFromPlanConstMeta,
        argValues: [name, waypoints, polylineEncoded, distanceM, durationS],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSaveRouteFromPlanConstMeta => const TaskConstMeta(
    debugName: "save_route_from_plan",
    argNames: [
      "name",
      "waypoints",
      "polylineEncoded",
      "distanceM",
      "durationS",
    ],
  );

  @override
  PlatformInt64 crateSaveTrip({
    required double distanceM,
    required PlatformInt64 durationSeconds,
    required PlatformInt64 startedAt,
    required PlatformInt64 completedAt,
    required String status,
    String? destinationLabel,
    String? routeId,
    String? polylineEncoded,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(distanceM, serializer);
          sse_encode_i_64(durationSeconds, serializer);
          sse_encode_i_64(startedAt, serializer);
          sse_encode_i_64(completedAt, serializer);
          sse_encode_String(status, serializer);
          sse_encode_opt_String(destinationLabel, serializer);
          sse_encode_opt_String(routeId, serializer);
          sse_encode_opt_String(polylineEncoded, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 46)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateSaveTripConstMeta,
        argValues: [
          distanceM,
          durationSeconds,
          startedAt,
          completedAt,
          status,
          destinationLabel,
          routeId,
          polylineEncoded,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSaveTripConstMeta => const TaskConstMeta(
    debugName: "save_trip",
    argNames: [
      "distanceM",
      "durationSeconds",
      "startedAt",
      "completedAt",
      "status",
      "destinationLabel",
      "routeId",
      "polylineEncoded",
    ],
  );

  @override
  Future<void> crateSendRouteToDevice({
    required PlatformInt64 deviceId,
    required String routeJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(deviceId, serializer);
          sse_encode_String(routeJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 47,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateSendRouteToDeviceConstMeta,
        argValues: [deviceId, routeJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSendRouteToDeviceConstMeta => const TaskConstMeta(
    debugName: "send_route_to_device",
    argNames: ["deviceId", "routeJson"],
  );

  @override
  Future<void> crateSetNavdspConfig({
    required String baseUrl,
    String? token,
    required bool geocodingEnabled,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_opt_String(token, serializer);
          sse_encode_bool(geocodingEnabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 48,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateSetNavdspConfigConstMeta,
        argValues: [baseUrl, token, geocodingEnabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSetNavdspConfigConstMeta => const TaskConstMeta(
    debugName: "set_navdsp_config",
    argNames: ["baseUrl", "token", "geocodingEnabled"],
  );

  @override
  Future<void> crateSetRoutingEngine({required String engine}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(engine, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 49,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateSetRoutingEngineConstMeta,
        argValues: [engine],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSetRoutingEngineConstMeta => const TaskConstMeta(
    debugName: "set_routing_engine",
    argNames: ["engine"],
  );

  @override
  Future<NavigationSessionDto> crateStartNavigationSession({
    required List<(double, double)> waypoints,
    required (double, double) currentPosition,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_record_f_64_f_64(waypoints, serializer);
          sse_encode_box_autoadd_record_f_64_f_64(currentPosition, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 50,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_navigation_session_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateStartNavigationSessionConstMeta,
        argValues: [waypoints, currentPosition],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateStartNavigationSessionConstMeta =>
      const TaskConstMeta(
        debugName: "start_navigation_session",
        argNames: ["waypoints", "currentPosition"],
      );

  @override
  Future<void> crateStopNavigation({required String sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 51,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateStopNavigationConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateStopNavigationConstMeta => const TaskConstMeta(
    debugName: "stop_navigation",
    argNames: ["sessionId"],
  );

  @override
  void crateUpdateDevice({
    required PlatformInt64 id,
    required String deviceJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          sse_encode_String(deviceJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 52)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateUpdateDeviceConstMeta,
        argValues: [id, deviceJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateUpdateDeviceConstMeta => const TaskConstMeta(
    debugName: "update_device",
    argNames: ["id", "deviceJson"],
  );

  @override
  Future<NavigationStateDto> crateUpdateNavigationPosition({
    required String sessionId,
    required double latitude,
    required double longitude,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_f_64(latitude, serializer);
          sse_encode_f_64(longitude, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 53,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_navigation_state_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateUpdateNavigationPositionConstMeta,
        argValues: [sessionId, latitude, longitude],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateUpdateNavigationPositionConstMeta =>
      const TaskConstMeta(
        debugName: "update_navigation_position",
        argNames: ["sessionId", "latitude", "longitude"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DerivedInstructionDto dco_decode_box_autoadd_derived_instruction_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_derived_instruction_dto(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  NavigationStateDto dco_decode_box_autoadd_navigation_state_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_navigation_state_dto(raw);
  }

  @protected
  (double, double) dco_decode_box_autoadd_record_f_64_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as (double, double);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  DerivedInstructionDto dco_decode_derived_instruction_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DerivedInstructionDto(
      kind: dco_decode_String(arr[0]),
      distanceToNextM: dco_decode_f_64(arr[1]),
      streetName: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GeocodingResultDto dco_decode_geocoding_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return GeocodingResultDto(
      latitude: dco_decode_f_64(arr[0]),
      longitude: dco_decode_f_64(arr[1]),
      displayName: dco_decode_String(arr[2]),
      name: dco_decode_opt_String(arr[3]),
      city: dco_decode_opt_String(arr[4]),
      country: dco_decode_opt_String(arr[5]),
      osmType: dco_decode_opt_String(arr[6]),
      osmId: dco_decode_opt_box_autoadd_i_64(arr[7]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<DerivedInstructionDto> dco_decode_list_derived_instruction_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_derived_instruction_dto)
        .toList();
  }

  @protected
  List<GeocodingResultDto> dco_decode_list_geocoding_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_geocoding_result_dto).toList();
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(double, double)> dco_decode_list_record_f_64_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_f_64_f_64).toList();
  }

  @protected
  List<WaypointDto> dco_decode_list_waypoint_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_waypoint_dto).toList();
  }

  @protected
  NavigationSessionDto dco_decode_navigation_session_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return NavigationSessionDto(
      id: dco_decode_String(arr[0]),
      route: dco_decode_route_dto(arr[1]),
      currentLatitude: dco_decode_f_64(arr[2]),
      currentLongitude: dco_decode_f_64(arr[3]),
      status: dco_decode_String(arr[4]),
    );
  }

  @protected
  NavigationStateDto dco_decode_navigation_state_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return NavigationStateDto(
      currentStep: dco_decode_u_32(arr[0]),
      currentInstruction: dco_decode_derived_instruction_dto(arr[1]),
      nextInstruction: dco_decode_opt_box_autoadd_derived_instruction_dto(
        arr[2],
      ),
      distanceToNextM: dco_decode_f_64(arr[3]),
      distanceRemainingM: dco_decode_f_64(arr[4]),
      etaSeconds: dco_decode_u_64(arr[5]),
      isOffRoute: dco_decode_bool(arr[6]),
      distanceFromRouteM: dco_decode_f_64(arr[7]),
      snappedLat: dco_decode_f_64(arr[8]),
      snappedLon: dco_decode_f_64(arr[9]),
      constraintAlerts: dco_decode_list_String(arr[10]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  DerivedInstructionDto? dco_decode_opt_box_autoadd_derived_instruction_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_derived_instruction_dto(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  NavigationStateDto? dco_decode_opt_box_autoadd_navigation_state_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_navigation_state_dto(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  (double, double) dco_decode_record_f_64_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_f_64(arr[0]), dco_decode_f_64(arr[1]));
  }

  @protected
  RouteDto dco_decode_route_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RouteDto(
      id: dco_decode_String(arr[0]),
      waypoints: dco_decode_list_waypoint_dto(arr[1]),
      distanceMeters: dco_decode_f_64(arr[2]),
      durationSeconds: dco_decode_u_32(arr[3]),
      polylineJson: dco_decode_String(arr[4]),
    );
  }

  @protected
  SessionStatsDto dco_decode_session_stats_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SessionStatsDto(
      totalDistanceM: dco_decode_f_64(arr[0]),
      totalDurationSeconds: dco_decode_i_64(arr[1]),
      sessionCount: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WaypointDto dco_decode_waypoint_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return WaypointDto(
      latitude: dco_decode_f_64(arr[0]),
      longitude: dco_decode_f_64(arr[1]),
      name: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DerivedInstructionDto sse_decode_box_autoadd_derived_instruction_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_derived_instruction_dto(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  NavigationStateDto sse_decode_box_autoadd_navigation_state_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_navigation_state_dto(deserializer));
  }

  @protected
  (double, double) sse_decode_box_autoadd_record_f_64_f_64(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_record_f_64_f_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  DerivedInstructionDto sse_decode_derived_instruction_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_distanceToNextM = sse_decode_f_64(deserializer);
    var var_streetName = sse_decode_opt_String(deserializer);
    return DerivedInstructionDto(
      kind: var_kind,
      distanceToNextM: var_distanceToNextM,
      streetName: var_streetName,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  GeocodingResultDto sse_decode_geocoding_result_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_latitude = sse_decode_f_64(deserializer);
    var var_longitude = sse_decode_f_64(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    var var_city = sse_decode_opt_String(deserializer);
    var var_country = sse_decode_opt_String(deserializer);
    var var_osmType = sse_decode_opt_String(deserializer);
    var var_osmId = sse_decode_opt_box_autoadd_i_64(deserializer);
    return GeocodingResultDto(
      latitude: var_latitude,
      longitude: var_longitude,
      displayName: var_displayName,
      name: var_name,
      city: var_city,
      country: var_country,
      osmType: var_osmType,
      osmId: var_osmId,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<DerivedInstructionDto> sse_decode_list_derived_instruction_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DerivedInstructionDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_derived_instruction_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<GeocodingResultDto> sse_decode_list_geocoding_result_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GeocodingResultDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_geocoding_result_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(double, double)> sse_decode_list_record_f_64_f_64(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(double, double)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_f_64_f_64(deserializer));
    }
    return ans_;
  }

  @protected
  List<WaypointDto> sse_decode_list_waypoint_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WaypointDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_waypoint_dto(deserializer));
    }
    return ans_;
  }

  @protected
  NavigationSessionDto sse_decode_navigation_session_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_route = sse_decode_route_dto(deserializer);
    var var_currentLatitude = sse_decode_f_64(deserializer);
    var var_currentLongitude = sse_decode_f_64(deserializer);
    var var_status = sse_decode_String(deserializer);
    return NavigationSessionDto(
      id: var_id,
      route: var_route,
      currentLatitude: var_currentLatitude,
      currentLongitude: var_currentLongitude,
      status: var_status,
    );
  }

  @protected
  NavigationStateDto sse_decode_navigation_state_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_currentStep = sse_decode_u_32(deserializer);
    var var_currentInstruction = sse_decode_derived_instruction_dto(
      deserializer,
    );
    var var_nextInstruction =
        sse_decode_opt_box_autoadd_derived_instruction_dto(deserializer);
    var var_distanceToNextM = sse_decode_f_64(deserializer);
    var var_distanceRemainingM = sse_decode_f_64(deserializer);
    var var_etaSeconds = sse_decode_u_64(deserializer);
    var var_isOffRoute = sse_decode_bool(deserializer);
    var var_distanceFromRouteM = sse_decode_f_64(deserializer);
    var var_snappedLat = sse_decode_f_64(deserializer);
    var var_snappedLon = sse_decode_f_64(deserializer);
    var var_constraintAlerts = sse_decode_list_String(deserializer);
    return NavigationStateDto(
      currentStep: var_currentStep,
      currentInstruction: var_currentInstruction,
      nextInstruction: var_nextInstruction,
      distanceToNextM: var_distanceToNextM,
      distanceRemainingM: var_distanceRemainingM,
      etaSeconds: var_etaSeconds,
      isOffRoute: var_isOffRoute,
      distanceFromRouteM: var_distanceFromRouteM,
      snappedLat: var_snappedLat,
      snappedLon: var_snappedLon,
      constraintAlerts: var_constraintAlerts,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DerivedInstructionDto? sse_decode_opt_box_autoadd_derived_instruction_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_derived_instruction_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  NavigationStateDto? sse_decode_opt_box_autoadd_navigation_state_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_navigation_state_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (double, double) sse_decode_record_f_64_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_f_64(deserializer);
    var var_field1 = sse_decode_f_64(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  RouteDto sse_decode_route_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_waypoints = sse_decode_list_waypoint_dto(deserializer);
    var var_distanceMeters = sse_decode_f_64(deserializer);
    var var_durationSeconds = sse_decode_u_32(deserializer);
    var var_polylineJson = sse_decode_String(deserializer);
    return RouteDto(
      id: var_id,
      waypoints: var_waypoints,
      distanceMeters: var_distanceMeters,
      durationSeconds: var_durationSeconds,
      polylineJson: var_polylineJson,
    );
  }

  @protected
  SessionStatsDto sse_decode_session_stats_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalDistanceM = sse_decode_f_64(deserializer);
    var var_totalDurationSeconds = sse_decode_i_64(deserializer);
    var var_sessionCount = sse_decode_i_64(deserializer);
    return SessionStatsDto(
      totalDistanceM: var_totalDistanceM,
      totalDurationSeconds: var_totalDurationSeconds,
      sessionCount: var_sessionCount,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WaypointDto sse_decode_waypoint_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_latitude = sse_decode_f_64(deserializer);
    var var_longitude = sse_decode_f_64(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    return WaypointDto(
      latitude: var_latitude,
      longitude: var_longitude,
      name: var_name,
    );
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_derived_instruction_dto(
    DerivedInstructionDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_derived_instruction_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_navigation_state_dto(
    NavigationStateDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_navigation_state_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_record_f_64_f_64(
    (double, double) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_record_f_64_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_derived_instruction_dto(
    DerivedInstructionDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_f_64(self.distanceToNextM, serializer);
    sse_encode_opt_String(self.streetName, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_geocoding_result_dto(
    GeocodingResultDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.latitude, serializer);
    sse_encode_f_64(self.longitude, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_opt_String(self.name, serializer);
    sse_encode_opt_String(self.city, serializer);
    sse_encode_opt_String(self.country, serializer);
    sse_encode_opt_String(self.osmType, serializer);
    sse_encode_opt_box_autoadd_i_64(self.osmId, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_derived_instruction_dto(
    List<DerivedInstructionDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_derived_instruction_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_geocoding_result_dto(
    List<GeocodingResultDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_geocoding_result_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_f_64_f_64(
    List<(double, double)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_f_64_f_64(item, serializer);
    }
  }

  @protected
  void sse_encode_list_waypoint_dto(
    List<WaypointDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_waypoint_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_navigation_session_dto(
    NavigationSessionDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_route_dto(self.route, serializer);
    sse_encode_f_64(self.currentLatitude, serializer);
    sse_encode_f_64(self.currentLongitude, serializer);
    sse_encode_String(self.status, serializer);
  }

  @protected
  void sse_encode_navigation_state_dto(
    NavigationStateDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.currentStep, serializer);
    sse_encode_derived_instruction_dto(self.currentInstruction, serializer);
    sse_encode_opt_box_autoadd_derived_instruction_dto(
      self.nextInstruction,
      serializer,
    );
    sse_encode_f_64(self.distanceToNextM, serializer);
    sse_encode_f_64(self.distanceRemainingM, serializer);
    sse_encode_u_64(self.etaSeconds, serializer);
    sse_encode_bool(self.isOffRoute, serializer);
    sse_encode_f_64(self.distanceFromRouteM, serializer);
    sse_encode_f_64(self.snappedLat, serializer);
    sse_encode_f_64(self.snappedLon, serializer);
    sse_encode_list_String(self.constraintAlerts, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_derived_instruction_dto(
    DerivedInstructionDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_derived_instruction_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_navigation_state_dto(
    NavigationStateDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_navigation_state_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_record_f_64_f_64(
    (double, double) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.$1, serializer);
    sse_encode_f_64(self.$2, serializer);
  }

  @protected
  void sse_encode_route_dto(RouteDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_list_waypoint_dto(self.waypoints, serializer);
    sse_encode_f_64(self.distanceMeters, serializer);
    sse_encode_u_32(self.durationSeconds, serializer);
    sse_encode_String(self.polylineJson, serializer);
  }

  @protected
  void sse_encode_session_stats_dto(
    SessionStatsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.totalDistanceM, serializer);
    sse_encode_i_64(self.totalDurationSeconds, serializer);
    sse_encode_i_64(self.sessionCount, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_waypoint_dto(WaypointDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.latitude, serializer);
    sse_encode_f_64(self.longitude, serializer);
    sse_encode_opt_String(self.name, serializer);
  }
}
