// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<String> searchRawJson({required String query, int? limit}) =>
    RustLib.instance.api.crateGeocodeSearchRawJson(query: query, limit: limit);

Future<List<FrbGeocodingResult>> searchTyped({
  required String query,
  int? limit,
}) => RustLib.instance.api.crateGeocodeSearchTyped(query: query, limit: limit);

class FrbGeocodingResult {
  final PlatformInt64 placeId;
  final String? licence;
  final String? osmType;
  final PlatformInt64? osmId;
  final String lat;
  final String lon;
  final String? displayName;
  final String? classField;
  final String? typeField;
  final double? importance;
  final List<String>? boundingbox;
  final Map<String, String>? address;

  const FrbGeocodingResult({
    required this.placeId,
    this.licence,
    this.osmType,
    this.osmId,
    required this.lat,
    required this.lon,
    this.displayName,
    this.classField,
    this.typeField,
    this.importance,
    this.boundingbox,
    this.address,
  });

  @override
  int get hashCode =>
      placeId.hashCode ^
      licence.hashCode ^
      osmType.hashCode ^
      osmId.hashCode ^
      lat.hashCode ^
      lon.hashCode ^
      displayName.hashCode ^
      classField.hashCode ^
      typeField.hashCode ^
      importance.hashCode ^
      boundingbox.hashCode ^
      address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbGeocodingResult &&
          runtimeType == other.runtimeType &&
          placeId == other.placeId &&
          licence == other.licence &&
          osmType == other.osmType &&
          osmId == other.osmId &&
          lat == other.lat &&
          lon == other.lon &&
          displayName == other.displayName &&
          classField == other.classField &&
          typeField == other.typeField &&
          importance == other.importance &&
          boundingbox == other.boundingbox &&
          address == other.address;
}
