// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MigrationManager`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `get_all_migrations`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `get_applied_versions`, `initialize`, `is_applied`, `migrate_down`, `migrate_up`, `migrate`, `new`, `rollback`, `status`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<str>>
abstract class Str implements RustOpaqueInterface {}

abstract class Migration {
  /// Returns a description of the migration
  Future<void> description();

  /// SQL to rollback the migration (optional)
  Future<Str?> down();

  /// SQL to apply the migration
  Future<void> up();

  /// Returns the version number (timestamp recommended: YYYYMMDDHHMMSS)
  Future<PlatformInt64> version();
}
