// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `stub_route`

/// Compute a route by trying the OSRM remote service first, and falling back
/// to a local hardcoded stub on any failure. The function is async so callers
/// can await it inside a tokio runtime.
Future<FrbRoute> computeRouteAsync({
  required double startLat,
  required double startLon,
  required double endLat,
  required double endLon,
  String? options,
}) => RustLib.instance.api.crateRouteComputeRouteAsync(
  startLat: startLat,
  startLon: startLon,
  endLat: endLat,
  endLon: endLon,
  options: options,
);
