// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Lightweight route DTO used across the FRB boundary.
class FrbRoute {
  final String id;

  /// Encoded polyline (polyline6 or polyline5 string). May be empty when
  /// the source provides geojson waypoints instead.
  final String polyline;
  final double distanceM;
  final double durationS;

  /// Human-friendly route name
  final String name;

  /// A small preview of waypoints as [lat, lon] pairs for quick display or
  /// testing.
  final List<F64Array2> waypoints;

  const FrbRoute({
    required this.id,
    required this.polyline,
    required this.distanceM,
    required this.durationS,
    required this.name,
    required this.waypoints,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      polyline.hashCode ^
      distanceM.hashCode ^
      durationS.hashCode ^
      name.hashCode ^
      waypoints.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbRoute &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          polyline == other.polyline &&
          distanceM == other.distanceM &&
          durationS == other.durationS &&
          name == other.name &&
          waypoints == other.waypoints;
}
