// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/entities.dart';
import '../domain/value_objects.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RegisterDeviceCommand`, `UpdateBatteryCommand`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PauseNavigationCommand>>
abstract class PauseNavigationCommand implements RustOpaqueInterface {
  UuidValue get sessionId;

  set sessionId(UuidValue sessionId);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ReportTrafficCommand>>
abstract class ReportTrafficCommand implements RustOpaqueInterface {
  int get delaySeconds;

  String get description;

  Position get position;

  UuidValue get sessionId;

  TrafficSeverity get severity;

  set delaySeconds(int delaySeconds);

  set description(String description);

  set position(Position position);

  set sessionId(UuidValue sessionId);

  set severity(TrafficSeverity severity);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ResumeNavigationCommand>>
abstract class ResumeNavigationCommand implements RustOpaqueInterface {
  UuidValue get sessionId;

  set sessionId(UuidValue sessionId);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SendRouteToDeviceCommand>>
abstract class SendRouteToDeviceCommand implements RustOpaqueInterface {
  String get deviceId;

  UuidValue get sessionId;

  set deviceId(String deviceId);

  set sessionId(UuidValue sessionId);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<StopNavigationCommand>>
abstract class StopNavigationCommand implements RustOpaqueInterface {
  bool get completed;

  UuidValue get sessionId;

  set completed(bool completed);

  set sessionId(UuidValue sessionId);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UpdatePositionCommand>>
abstract class UpdatePositionCommand implements RustOpaqueInterface {
  Position get position;

  UuidValue get sessionId;

  set position(Position position);

  set sessionId(UuidValue sessionId);
}

/// Start a new navigation session
class StartNavigationCommand {
  final List<Position> waypoints;
  final Position currentPosition;
  final String? deviceId;

  const StartNavigationCommand({
    required this.waypoints,
    required this.currentPosition,
    this.deviceId,
  });

  @override
  int get hashCode =>
      waypoints.hashCode ^ currentPosition.hashCode ^ deviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StartNavigationCommand &&
          runtimeType == other.runtimeType &&
          waypoints == other.waypoints &&
          currentPosition == other.currentPosition &&
          deviceId == other.deviceId;
}
