// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/value_objects.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GetConnectedDevicesQuery`, `GetDeviceQuery`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GetSessionQuery>>
abstract class GetSessionQuery implements RustOpaqueInterface {
  UuidValue get sessionId;

  set sessionId(UuidValue sessionId);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GetTrafficAlertsQuery>>
abstract class GetTrafficAlertsQuery implements RustOpaqueInterface {
  UuidValue get sessionId;

  set sessionId(UuidValue sessionId);
}

/// Calculate route without starting navigation
class CalculateRouteQuery {
  final List<Position> waypoints;

  const CalculateRouteQuery({required this.waypoints});

  @override
  int get hashCode => waypoints.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalculateRouteQuery &&
          runtimeType == other.runtimeType &&
          waypoints == other.waypoints;
}

/// Geocode an address
class GeocodeQuery {
  final String address;

  const GeocodeQuery({required this.address});

  @override
  int get hashCode => address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GeocodeQuery &&
          runtimeType == other.runtimeType &&
          address == other.address;
}

/// Get active navigation session
class GetActiveSessionQuery {
  const GetActiveSessionQuery();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GetActiveSessionQuery && runtimeType == other.runtimeType;
}

/// Reverse geocode a position
class ReverseGeocodeQuery {
  final Position position;

  const ReverseGeocodeQuery({required this.position});

  @override
  int get hashCode => position.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReverseGeocodeQuery &&
          runtimeType == other.runtimeType &&
          position == other.position;
}
