// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/ports.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they have generic arguments: `geocode`, `reverse_geocode`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PhotonGeocodingService>>
abstract class PhotonGeocodingService
    implements RustOpaqueInterface, GeocodingService {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<PhotonGeocodingService> newInstance({
    required String baseUrl,
  }) => RustBridge.instance.api
      .crateInfrastructureGeocodingAdapterPhotonGeocodingServiceNew(
        baseUrl: baseUrl,
      );
}
