// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/ports.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they have generic arguments: `delete_session`, `load_active_session`, `load_session`, `save_session`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InMemoryNavigationRepository>>
abstract class InMemoryNavigationRepository
    implements RustOpaqueInterface, NavigationRepository {
  static Future<InMemoryNavigationRepository> default_() => RustBridge
      .instance
      .api
      .crateInfrastructureInMemoryRepoInMemoryNavigationRepositoryDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<InMemoryNavigationRepository> newInstance() => RustBridge
      .instance
      .api
      .crateInfrastructureInMemoryRepoInMemoryNavigationRepositoryNew();
}
