// This file contains app version constants
// In production builds, this file is auto-generated by GitHub Actions

class AppVersion {
  static const String version = 'dev';
  static const String tag = 'development';
  static const String buildDate = 'development';
  static const String? githubSha = null;
}
