name: Publish on Tag
on:
  push:
    tags: ['v*.*.*']
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { channel: stable }
      - run: flutter pub get
      - run: flutter build apk --release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/web/**/*
