name: Close stale
on: schedule: [{ cron: "0 3 * * 1" }]
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 30
          days-before-close: 7
          stale-issue-label: "stale"
          exempt-issue-labels: "priority:P0,help wanted,good first issue"
